import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="hidden h-full md:flex md:flex-col font-medium fixed md:inset-y-0 md:w-52">
            <Sidebar />
          </div>

          <div className="md:ml-52">
            <Navbar />
          </div>
          <main className="md:ml-52 p-2">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
